### ISSUE TITLE
Add a Clone method

### ISSUE THREAD

**Issue by seesharper** [seesharper/LightInject#251]
Makes it possible to create a clone of a container with the same configuration as the "parent" container.

```
var clonedContainer = serviceContainer.Clone();
```

**Comment by DmitriiGaidukov** [comment]
Please tell me will it be good to use a Clone method for solving my problem. 
I'm starting a long-running Task from the code in a web method. After that the web method without waiting for the end of the task return success result and finish its work, while the Task is continuing running. The problem is that task's code is resolving scoped dependences through container. But it's impossible since the web method has finished it's work and closed the scope.
I come across the Clone method and wonder if I can solve my problem by cloning the container in order to be able to resolve scoped dependecies after the scope is closed. I've tried it out and it seems be working, but with such side effect that if I call dispose on cloned container then stackoverflowexception happens.
