### ISSUE TITLE
LightInject.Nancy has to keep the order of registered implementations

### ISSUE THREAD

**Issue by xmedeko** [seesharper/LightInject#268]
Nancy need to keep the order of registered implementation types, see https://github.com/NancyFx/Nancy.Serialization.JsonNet/issues/36 

Also see https://github.com/NancyFx/Nancy.Bootstrappers.Autofac/blob/master/src/Nancy.Bootstrappers.Autofac/AutofacNancyBootstrapper.cs and where the `PreserveExistingDefaults()` method is used.

**Comment by seesharper** [comment]
I look into it although I got to say that I find it strange that Nancy relies of the ordering of a sequence not controlled by Nancy itself.

**Comment by xmedeko** [comment]
I agree, the `GetAllInstances()` result should not depend on the order of registration. What about to register `IEnumerable<>` instead of registering one by one in the foreach cycle.

**Comment by seesharper** [comment]
That is probably a good way to do it. Can we come up with a failing test for this somehow?

**Comment by xmedeko** [comment]
I am not sure how it would fit to other Nancy parts. E.g. they recommend to [register s custom serializer](https://github.com/NancyFx/Nancy.Serialization.JsonNet):
```c#
container.Register<JsonSerializer, CustomJsonSerializer>();
```
And do not know how such registration is handled inside Nancy. IMO we need someone from Nancy team to discuss the issue and solution.

**Comment by seesharper** [comment]
Maybe @khellang could elaborate on this? Although the adapter(bootstrapper) is pretty simple, there are no tests provided by Nancy that verifies the behavior of the adapter. This should not only be be the case for the ordering of multiple services, but also for all behavior expected from the adapter. The new DI abstraction for ASP.NET Core for instance, provides  test suite that every container adapter can use to verify the correctness of each adapter. That would be a great addition to Nancy.

**Comment by khellang** [comment]
> I got to say that I find it strange that Nancy relies of the ordering of a sequence not controlled by Nancy itself.

This isn't something we normally do. It just happened to be the behavior of a method for hard-coding the return value of a module to JSON/XML.

> What about if the LightInject.Nancy would be moved to Nancy project as Nancy.Bootstrappers.LightInject ? They maintain the support for a few other containers already.

This is something we've been trying to get away from for ages. We started the initiative to find external bootstrapper owners (https://github.com/NancyFx/Nancy/issues/1712) a long time ago, but haven't really gotten to the point where we've assigned anyone yet. We could move the bootstrapper, but we wouldn't want to maintain it. We're no LightInject experts (nor are we Unit, Windsor or Ninject experts), so we'd rather see the community own it.

> Although the adapter(bootstrapper) is pretty simple, there are no tests provided by Nancy that verifies the behavior of the adapter. This should not only be be the case for the ordering of multiple services, but also for all behavior expected from the adapter.

This is something that was also started a long time ago, but never came through. You can see the start [here](https://github.com/NancyFx/Nancy/blob/master/test/Nancy.Tests/Unit/Bootstrapper/Base/BootstrapperBaseFixtureBase.cs). Unfortunately, the current bootstrapper design has a few too many assumptions about containers that are very hard to test. We're working on a new bootstrapper design for an upcoming version of Nancy (if you're interested, you can see it at [nancy-bootstrapper-prototype](https://github.com/khellang/nancy-bootstrapper-prototype)). This design will make fewer assumptions about the container and thus make more of them compatible and the bootstrapper implementation easier to implement. Because of this, I don't think you'll see us putting out an extensive test suite for the current design. Hopefully we'll get something going for the new one :smile:

**Comment by xmedeko** [comment]
>> I got to say that I find it strange that Nancy relies of the ordering of a sequence not controlled by Nancy itself.

> This isn't something we normally do. It just happened to be the behavior of a method for hard-coding the return value of a module to JSON/XML.

Are you sure the ordering of sequence is necessary just for the serializers? What about the `NancyBootstrapperBase.RegisterAndGetRequestStartupTasks()`?

**Comment by khellang** [comment]
> Are you sure the ordering of sequence is necessary just for the serializers? What about the `NancyBootstrapperBase.RegisterAndGetRequestStartupTasks()`?

What about it? Ideally, we'd only register the default serializers if no custom serializer was found. The problem is that there's no way for us to know whether one serializer is a strict replacement of another. That's why we sometimes have to do `serializers.FirstOrDefault(x => x.CanSerialize("application/json"))`-style picking. If we had separate interfaces for `IJsonSerializer` and `IXmlSerializer`, it'd be easy, but that would also make the abstraction worse. What about the ProfoBuf serializer? We don't provide a default, but you could easily plug one in.

**Comment by xmedeko** [comment]
@khellang Is the ordering of sequence constraint put on the container relay necessary for Nancy or may it be removed in the future? It's not about just serializers, it's also about the other parts of Nancy (I guess `IStatusCodeHandler`, `IRequestStartup`, ... ), which rely on the fact, that the container resolves the sequences in the given order.

**Comment by khellang** [comment]
Hopefully we won't have to rely on it in the future. As I mentioned, the serializers are a special case, because it's hard to know which serializer can replace which. For status code handlers etc., we can check if there's a custom instance, otherwise we can fall back to the default. (see [NancyEngine](https://github.com/NancyFx/Nancy/blob/master/src/Nancy/NancyEngine.cs#L248)).

**Comment by khellang** [comment]
Also, you know that you can just opt out of the whole scanning mechanism? If you override the serializer types, you can explicitly define which serializers you want in your app:

```csharp
protected override NancyInternalConfiguration InternalConfiguration
{
    get
    {
        return NancyInternalConfiguration.WithOverrides(config =>
        {
            config.Serializers = new[] { typeof(GetMeSomeFancyResponseSerializer), typeof(AwesomeCustomSerializer) };
        });
    }
}
```

**Comment by seesharper** [comment]
That certainly seems like a reasonably good workaround for now.

**Comment by xmedeko** [comment]
So `LightInject.Nancy` together with `Nancy.Serialization.JsonNet` needs the additional setup to work correctly. This issue can be closed, since the problem will be solved in Nancy.
