### ISSUE TITLE
NServiceBus Support

### ISSUE THREAD

**Issue by joefeser** [seesharper/LightInject#279]
We were looking at rolling our own wrapper for NServiceBus but we ran into a lot of issues.

NServiceBus really wants to work with child containers and LightInject does not support this feature.

It looks like NestedContainers is not a solution due to the need for multiple nested containers at the same time.

Any suggestions would be helpful.

Thank you

**Comment by seesharper** [comment]
I did a serious attempt at this about a year ago. I can't quite remember, but I think it passed all the tests. They have a NuGet package containing the integration tests. Then one day my trial license ran out and I was unable to continue the work with NServiceBus. Since they don't or at least didnt' at the time, provide an OSS license, I decided to put this work on hold. The thing is that LightInject is open source, MIT licensed and I simply cannot rely on a valid license for a third party commercial product unless they also provide an OSS license. I have not looked into this since then so that it may very well be that they have changed their licensing model. I that case I would be happy to help you out :)

**Comment by joefeser** [comment]
Is there a way you can publish the source somewhere or email me a zip of the source? It is a pain that they will not provide you with a license.

**Comment by valeriob** [comment]
Hi @joefeser did you make any progress about it?

**Comment by joefeser** [comment]
Nope gave up and moved to autofac

**Comment by valeriob** [comment]
I'm coming from autofac and i wanted to try an alternative, too bad.
Maybe @seesharper can release the code he was talking about so we can check it out ?

**Comment by seesharper** [comment]
https://github.com/Particular/NServiceBus/issues/3824

**Comment by seesharper** [comment]
I have create a rep for this where I have put what I have got so far. It passes all the container tests for NServiceBus 5.x. https://github.com/seesharper/LightInject.NServiceBus

There are still more work to be done here as I am not sure that the container tests actually cover every possible scenario. But at least you should be able to play with this integration now. Just copy the source file into your project and feed the LightInjectObjectBuilder to the NServiceBus config.

**Comment by valeriob** [comment]
Thanks !

**Comment by seesharper** [comment]
I have created an issue in the new repo where we can continue the discussion.
https://github.com/seesharper/LightInject.NServiceBus/issues/1

There are still a few things that needs clarification

**Comment by seesharper** [comment]
LightInject is now the default container in NServiceBus

**Comment by valeriob** [comment]
so how do we use LightInject with nservicebus ? 😄
