### ISSUE TITLE
Property Injection doesn't work in ASP.NET core rc2 app

### ISSUE THREAD

**Issue by ivankarpey** [seesharper/LightInject#284]
Not much to say except information in the header. So currently property injection not working. I was trying to use LightInject.Annotations to force it, but seems this project not adopted for rc2 at all.

Also there is a bit unclear from docs, does lightinject support protected property injection somehow?

[Code for easily verifying the problem](https://github.com/ivankarpey/LightInjectIssue)

**Comment by seesharper** [comment]
This is because the controllers are not really created by LightInject. 

Take a look here for more information about this issue.
http://www.strathweb.com/2016/03/the-subtle-perils-of-controller-dependency-injection-in-asp-net-core-mvc/

In your case you need to register dependencies in the service collection rather than directly with LightInject. The controller instance is created by asp.net core and its dependencies are created by calling into the DI abstraction which is LightInject in this case. That is wierd, I know, but that is the current state of things in ASP.NET Core. While it might be possible to have ALL the services, including the controllers to be resolved through LightInject, this is something I am going to look into once it RTM's. They are most probably going to move my cheese at least twice before RTM :)
