### ISSUE TITLE
Functional Dependency Injection

### ISSUE THREAD

**Issue by Rajivhost** [seesharper/LightInject#337]
Hi,
How if I want to handle such case:

![image](https://cloud.githubusercontent.com/assets/3539984/20867062/2d53276a-ba3c-11e6-80d1-91c1af202ab9.png)

On the Cqrs approach for example, on the functional way.

**Comment by Rajivhost** [comment]
Here some examples:
https://github.com/justmoon/reduct
http://fsharpforfunandprofit.com/posts/dependency-injection-1/

**Comment by seesharper** [comment]
Functional Dependency Injection is mostly used with functional languages like F#, Javascript and so on. If I understand correctly you want the dependencies to be injected into the method rather than taking the dependencies into the class constructor? What is the scenario fro this? Any particular reason you don't want to do constructor injection which by far is the most common way of doing dependency injection
