### ISSUE TITLE
LightInject 5.0.0 + WebApi: Attempt to end a scope that is currently not the current scope exception

### ISSUE THREAD

**Issue by RomanDidenko** [seesharper/LightInject#339]
With LightInject 5.0.0 code base (.Net 4.6) I see "Attempt to end a scope that is currently not the current scope" exception on web api 2 project. The issue is not reproducible with 4.1.0.

I was not able to figure out the cause of the issue and prepared very simple test web.api project: https://github.com/RomanDidenko/LightInject5.Exception

**Comment by stefan505** [comment]
I have exactly the same issue and I'm 99% sure its because the Thread id changes. I also prepared repro project with a `await Task.Delay(10)' call in it and get the same error. 

I logged [this](https://github.com/seesharper/LightInject.Microsoft.DependencyInjection/issues/9) issue detailing what I've found. 

My repro wasn't giving the same error, but its because initially I was stepping through the code slowly, which sometimes doesn't result in a thread id change. If I just let my repro app run, it fails with this error.

**Comment by RomanDidenko** [comment]
Interesting that I do not see the issue with 4.1.0 version of LightInject. Try to run your test 4.1.0 LightInject, please. Do you still see same issue using older version?

**Comment by stefan505** [comment]
No, I never had the error on 4.1.0, but the app was targeting the ASP.NET Core 1.0 assemblies. I've upgraded everything to 1.1 recently.

**Comment by seesharper** [comment]
Since this is an Owin application, we could simply create a scope manager that stores the current scope with the IOwinContext. 

```
    public class ContextMiddleware : OwinMiddleware
    {
        public static readonly AsyncLocal<IOwinContext> CurrentOwinContext = new AsyncLocal<IOwinContext>();

        public ContextMiddleware(OwinMiddleware next) : base(next)
        {
        }

        public override async Task Invoke(IOwinContext context)
        {
            CurrentOwinContext.Value = context;
            await Next.Invoke(context);
            CurrentOwinContext.Value = null;
        }
    }

    internal class PerOwinContextScopeManager : ScopeManager
    {
        private const string ScopeKey = "LightInject.Scope";

        public PerOwinContextScopeManager(IServiceFactory serviceFactory) : base(serviceFactory)
        {
        }

        public override Scope CurrentScope
        {
            get
            {
                var currentContext = ContextMiddleware.CurrentOwinContext.Value;            
                return currentContext?.Get<Scope>(ScopeKey);
            }
            set
            {
                var currentContext = ContextMiddleware.CurrentOwinContext.Value;
                currentContext?.Set(ScopeKey, value);
            }
        }
    }

    internal class PerOwinContextScopeManagerProvider : ScopeManagerProvider
    {
        protected override IScopeManager CreateScopeManager(IServiceFactory serviceFactory)
        {
            return new PerOwinContextScopeManager(serviceFactory);
        }
    }
```

The ContextMiddleware is simply just a middleware that captures the current IOwinContext.

The startup class would then look like this 

```
    public class Startup
    {
        public void Configuration(IAppBuilder appBuilder)
        {
            var config = new HttpConfiguration();

            var container = new ServiceContainer();
            container.Register<IFoo, Foo>(new PerScopeLifetime());

            container.RegisterApiControllers();
            container.EnableWebApi(config);
            container.ScopeManagerProvider = new PerOwinContextScopeManagerProvider();

            config.Routes.MapHttpRoute(
                name: "DefaultApi",
                routeTemplate: "{controller}/{id}",
                defaults: new { id = RouteParameter.Optional, controller = "default" }
            );
            // Insert out middleware at the beginning of the owin pipeline
            appBuilder.Use<ContextMiddleware>();
            appBuilder.UseWebApi(config);
         }
    }
```

**Comment by petersondrew** [comment]
Is there a workaround for things that don't have such a nice clean scope? I'm starting to do some work with Akka actors, using LightInject to inject dependencies into the actors, and I'm hitting this bug when actors are restarted. Disposing of the scope throws the exception mentioned above.

**Comment by petersondrew** [comment]
So, I was looking into it more, and it seems the regardless of which scopemanager is used, the base scopemanager expects the current scope to be the scope that is passed to EndScope. I can see there are a few places, such as `Scope.WithThisScope` where there's a little dance around CurrentScope, is the expectation that we have to get a handle on the current scope manager and change the current scope before disposing of a scope that we've stashed away somewhere? It seems there are also some threading concerns around scopes in general, given that the scope class messes with CurrentScope on the scopemanager any time GetInstance is called on that scope. It seems that if you're using multiple threads, using scopes is sort of a no-no?

**Comment by seesharper** [comment]
Hi Drew.

Investigating this now.

**Comment by seesharper** [comment]
This is very much related to the following issue where in some cases ASP.NET Core might end a scope on a different logical thread context. 

https://github.com/seesharper/LightInject.Microsoft.DependencyInjection/issues/9

The scoping mechanism has been a subject for major changes in order to support requesting services directly off the scope which in turn has made LightInject easier to integrate with frameworks that manages its own scopes such as  Microsoft.Extensions.DependencyInjection.

As of LightInject 5.0.1 it will be possible to end the scope on another context (threadlocal or asynclocal) as it was in LightInject prior to the scope refactoring done in 5.0.0
