### ISSUE TITLE
PerScopeLifetime in webapi is not working

### ISSUE THREAD

**Issue by asafp** [seesharper/LightInject#402]
when using PerScopeLifetime inside webapi2 framework 4.6.2
i get multiple instances created in the same web request.
when initializing the container i used the following code:
 container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();

still i get multiple instances of my service
any ideas?

**Comment by seesharper** [comment]
Could you provide a full example? The simplest this that does not work :)

**Comment by mbenus** [comment]
I'm having issues also.
My webservice project gives me the runtime error when migrating from lightinject v4 towards 5.1.2 and lightinject.wcf v1 towards ligtinject.wcf v2.0.0
Could not load type 'LightInject.PerLogicalCallContextScopeManagerProvider' from assembly 'LightInject, Version=5.1.2.0, Culture=neutral, PublicKeyToken=null'.

When I manually try to set the ScopeManager on my container, "PerLogicalCallContextScopeManagerProvider" is an option to select, but it cannot be found in the namespace LightInject:

var container = new ServiceContainer();
container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();

Error	CS0234	The type or namespace name 'PerLogicalCallContextScopeManagerProvider' does not exist in the namespace 'LightInject' (are you missing an assembly reference?)

**Comment by mbenus** [comment]
I dived into the code of LightInject:
https://github.com/seesharper/LightInject/blob/master/src/LightInject/LightInject.cs

And "PerLogicalCallContextScopeManagerProvider" is only used for particular dotNet versions.
Caused by the phrase:
#if NET452 || NETSTANDARD1_3 || NETSTANDARD1_6 || NET46
...

The solution in my case was upgrading the dotnet framework towards 4.5.2 or 4.6
