### ISSUE TITLE
Decorator patter with a lifetime that doesn't match the default

### ISSUE THREAD

**Issue by bounav** [seesharper/LightInject#478]
Is it possible to use the decorator pattern and specify a lifetime at the same time?

```csharp
registry.SetDefaultLifetime<PerScopeLifetime>();

registry.Register<IFoo, Foo>(new PerContainerLifestyle());
registry.Decorate<IFoo, FooCache>(); // It seems foo cache will have a scope lifetime and there is no overload to specify the lifetime of FooCache.
```

I tried doing `registry.Register<FooCache, FooCache>(new PerContainerLifetime());` before calling the `.Decorate<,>()` method but it doesn't seem to make a difference.

When I then call `factory.GetInstance<IFoo>()` it complains that I'm trying to resolve a type without a scope.

Is anyone having similar issues?

**Comment by seesharper** [comment]
Hi @bounav 

Decorators follow the same lifetime as the services they decorate. This is by design. 

In your case I would create an `ICache`service and inject that into the `FooCache´. The `ICache` could be a singleton (PerContainerLifetime). Otherwise you could do simpler approach with just a static `ConcurrentDictionary` inside your `FooCache`. Personally I like the `ICache` solution as it opens up for a way to invalidate the cache. Makes sense?

**Comment by bounav** [comment]
Hello,

Thanks for clarifying. I'll give your suggestions a go ;)
