### ISSUE TITLE
`IAsyncDisposable` Support?

### ISSUE THREAD

**Issue by Mike-E-angelo** [seesharper/LightInject#560]
Greetings,

Looking through the issues and I do not see any mention of `IAsyncDisposable`.  I do see this issue:

https://github.com/dotnet/extensions/issues/1751

But it does not look like anything definitive was made from that conversation.

I would like to create this issue to track this.

Thank you for any consideration. 🙏

**Comment by seesharper** [comment]
Hi @Mike-E-angelo and happy news years although a little late :)

Yeah, you@re right. This is something that should have been implemented for quite some time. 

Right now I'm trying to clean up all the TFM's in LightInject. 

Up until now I've had all these target frameworks in the test project in order to test all different TFM's in LightInject. 

Supporting different version of `netstandard` is a big pain in the b.... 😀. Even worse when it comes to testing. 

But then I came across this on SO https://stackoverflow.com/questions/48526219/is-there-a-way-to-force-a-project-reference-to-net-standard-project-to-a-specif

I assume that's you. You always have this politeness and a positive spin I wish I saw more of in the OSS community 👍

Anyways, `IAsyncDisposable` is next once I've clean up my test projects

**Comment by Mike-E-angelo** [comment]
Awww thank you for that @seesharper, that really means a lot and made my day!  I am still grateful for your efforts in https://github.com/seesharper/LightInject.Microsoft.AspNetCore.Hosting/issues/54 and am still amazed you took the extra effort of actually installing an Oauth application to get it to reproduce.  I was actually thinking about that last month or so and how cool that was and thought for sure I was up a creek with that issue.  But to the contrary, it is the only issue I encountered and everything has been working great with LightInject since!

Incidentally, I am still working on that same application and LightInject is very much a part of it.  It's been two years of full development and I am about to post and make an announcement in a few weeks' time.  I'll be sure to update here with the info. :)

BACK ON TOPIC HERE 😅... sounds good on the rest.  I've had to do some workarounds to get `IAsyncDisposable` working but having it as a first-class feature from the DI container would be great and most definitely appreciated.  Looking forward to any progress. 👍

**Comment by Mike-E-angelo** [comment]
>  I'll be sure to update here with the info. :)

FWIW I announced this product yesterday:
https://blog.starbeam.one/2022/02/announcing-mvp-alpha-preview/

And LightInject is mentioned in my acknowledgements here:
https://alpha.starbeam.one/about/acknowledgements

**Comment by seesharper** [comment]
@Mike-E-angelo `IAsyncDisposable` in LightInject 👍😃 #573

**Comment by Aragas** [comment]
There's an issue with it! net462 and netstandard2.0 do not support both IAsyncDisposable and ValueTask, so they are broken now!

**Comment by Aragas** [comment]
Could this be enabled/disabled via an define variable? We can't afford to import `Microsoft.Bcl.AsyncInterfaces`!

**Comment by seesharper** [comment]
You can conditionally add the package like it is done in `LightInject.csproj`

```
 <ItemGroup Condition=" '$(TargetFramework)' == 'net462' OR '$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="6.0.0" />
  </ItemGroup>
```

**Comment by Aragas** [comment]
I understand, we but can't add new dependencies. We use LightInject.Source because it didn't introduce any external dependencies

**Comment by seesharper** [comment]
I understand. We will enable this only for `netcoreapp3.1` and above 👍😃 https://github.com/seesharper/LightInject/pull/574

**Comment by Mike-E-angelo** [comment]
Very awesome @seesharper !  Thank you very very much for attending to this. 👍  Unfortunately my codebase is baked and fried at this point but I will definitely keep it in mind going forward. :D
